stages:
  - frontend
  - backend
  - terraform-infra
  - terraform-helm

frontend root:
  stage: frontend
  artifacts:
    name: frontend-pipeline
    paths:
      - gke-terraform-helm/frontend-app-master/.gitlab-ci.yml

backend root:
  stage: backend
  artifacts:
    name: backend-pipeline
    paths:
      - gke-terraform-helm/backend-app-master/.gitlab-ci.yml

terraform infra root:
  stage: terraform-infra
  artifacts:
    name: terraform-infra-pipeline
    paths:
      - gke-terraform-helm/gke-tf-infra/.gitlab-ci.yml


terraform helm root:
  stage: terraform-helm
  artifacts:
    name: terraform-helm-pipeline
    paths:
      - gke-terraform-helm/gke-tf-helm/.gitlab-ci.yml
