stages:
  - frontend
  - backend
  - terraform-infra
  - terraform-helm

frontend root:
  stage: frontend
  trigger:
    include: frontend-app-master/.gitlab-ci.yml

backend root:
  stage: backend
  trigger:
    include: backend-app-master/.gitlab-ci.yml

terraform infra root:
  stage: terraform-infra
  trigger:
    include: gke-tf-infra/.gitlab-ci.yml
  needs:
    - job: backend root
      artifacts: true
  

terraform helm root:
  stage: terraform-helm
  trigger:
    include: gke-tf-helm/.gitlab-ci.yml
  needs:
    - job: terraform infra root
      artifacts: true
