image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - frontend
  - backend
  - terraform-infra
  - terraform-helm

frontend root:
  stage: frontend
  trigger:
    project: gke-terraform-helm/frontend-app-master/.gitlab-ci.yml

backend root:
  stage: backend
  trigger:
    project: gke-terraform-helm/backend-app-master/.gitlab-ci.yml

terraform infra root:
  stage: terraform-infra
  trigger:
    project: gke-terraform-helm/gke-tf-infra/.gitlab-ci.yml

terraform helm root:
  stage: terraform-helm
  trigger:
    project: gke-terraform-helm/gke-tf-helm/.gitlab-ci.yml